(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const i of t)if(i.type==="childList")for(const l of i.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function n(t){const i={};return t.integrity&&(i.integrity=t.integrity),t.referrerPolicy&&(i.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?i.credentials="include":t.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function a(t){if(t.ep)return;t.ep=!0;const i=n(t);fetch(t.href,i)}})();const m=3,f=.005,g=[{path:"$",types:["object"],present_in:3},{path:"$.error",types:["string"],present_in:1},{path:"$.job",types:["object"],present_in:1},{path:"$.job.attempt",types:["integer"],present_in:1},{path:"$.job.name",types:["string"],present_in:1},{path:"$.job.ok",types:["boolean"],present_in:1},{path:"$.level",types:["string"],present_in:3},{path:"$.region",types:["string"],present_in:1},{path:"$.request",types:["object"],present_in:2},{path:"$.request.authorization",types:["string"],present_in:1},{path:"$.request.latency_ms",types:["integer"],present_in:2},{path:"$.request.method",types:["string"],present_in:2},{path:"$.request.path",types:["string"],present_in:2},{path:"$.request.user_email",types:["string"],present_in:1},{path:"$.service",types:["string"],present_in:3},{path:"$.timestamp",types:["string"],present_in:3},{path:"$.trace_id",types:["string"],present_in:1}],y=[{path:"$.request.authorization",detector:"secret-shaped value",confidence:"high",action:"Mask this value or exclude the field."},{path:"$.request.authorization",detector:"sensitive field name",confidence:"high",action:"Review this field before forwarding."},{path:"$.request.user_email",detector:"email-shaped value",confidence:"medium",action:"Confirm that this identifier belongs in the drain."}],b=[{days:7,estimated_bytes:571536,display:"558.1 KiB"},{days:30,estimated_bytes:2449440,display:"2.3 MiB"}],s={events:m,events_per_second:f,fields:g,findings:y,retention:b},o=document.querySelector("#app"),v=()=>document.querySelector("#route-status"),w="7f4d941baa0e",d=r=>`<a class="skip" href="#main">Skip to content</a>
  <header>
    <a class="wordmark" href="/" data-route aria-label="Drain Check home">DRΛIN<br>CHECK</a>
    <nav aria-label="Main navigation">
      <a href="/?demo=1" data-route>Demo</a><a href="/#how">How it works</a><a href="/privacy" data-route>Privacy</a>
    </nav>
  </header>
  ${r}
  <footer>
    <p>Drain Check samples a log drain before you forward it.</p>
    <p><a href="/privacy" data-route>Privacy</a><span aria-hidden="true"> · </span><a href="/terms" data-route>Terms</a><span aria-hidden="true"> · </span>Built by Param Factory<span aria-hidden="true"> · </span>v0.1.0+${w}</p>
  </footer>
  <div id="route-status" class="sr-only" aria-live="polite"></div>`;function p(r,e,n){document.title=r,document.querySelector('meta[name="description"]').content=e,document.querySelector('link[rel="canonical"]').href=`https://log-drain-contract-check.sociobot.in${n}`,document.querySelector('meta[property="og:title"]').content=r,document.querySelector('meta[property="og:description"]').content=e,document.querySelector('meta[name="twitter:title"]').content=r,document.querySelector('meta[name="twitter:description"]').content=e}function $(){return p("Drain Check — inspect a log drain sample","Inspect a bounded local log drain sample before forwarding it.","/"),d(`<main id="main" tabindex="-1">
    <section class="hero">
      <div class="hero-copy">
        <p class="eyebrow">LOCAL 10-MINUTE SAMPLE</p>
        <h1 tabindex="-1">Inspect a log drain before forwarding</h1>
        <p class="lede">For platform teams checking volume, field types, and sensitive data before enabling a log drain.</p>
        <p class="hero-action"><a class="button primary" href="/?demo=1" data-route>Try it with sample data</a><span class="button-note">Opens the bundled report. Writes no browser data.</span></p>
        <ul class="facts"><li>The receiver binds to <code>127.0.0.1</code>.</li><li>Accepted bodies are discarded by default.</li><li>Free under the MIT License.</li></ul>
      </div>
      <figure class="hero-art"><img src="/drain-console.webp" width="1024" height="1024" fetchpriority="high" alt="A pixel-art local receiver sorts log packets into review lanes."><figcaption>THE RECEIVER STAYS LOCAL</figcaption></figure>
    </section>
    <section class="terminal" tabindex="0" aria-labelledby="run-title" aria-describedby="run-help">
      <div class="terminal-bar"><span aria-hidden="true">●</span><span id="run-title">bundled sample / recorded run</span><button id="replay-demo" type="button">Replay recording</button></div>
      <p id="run-help" class="sr-only">A text recording of the bundled CLI demo. Use the replay button to play it again.</p>
      <pre tabindex="0"><code id="terminal-output">$ drain-check demo
Reviewed 3 events in 600s. 17 fields. 3 findings across 2 fields.
Report: /tmp/drain-check-demo-[unique]/report.json

$ drain-check forwarding --url https://receiver.example/logs
# generic-http
# Send POST requests to this endpoint after report review
url = "https://receiver.example/logs"
method = "POST"
content_type = "application/json"</code></pre>
    </section>
    <section id="how" class="steps" aria-labelledby="how-title">
      <p class="eyebrow">HOW IT WORKS</p><h2 id="how-title">Review a drain in three steps</h2>
      <ol><li><strong>Listen locally.</strong><br>Run one bounded window.</li><li><strong>Review the report.</strong><br>Check fields and likely sensitive data.</li><li><strong>Generate a forwarding configuration.</strong><br>Review the generated configuration.</li></ol>
    </section>
    <section class="limits" aria-labelledby="limits-title"><h2 id="limits-title">What Drain Check does not retain</h2><p>The receiver discards accepted bodies after aggregation by default.</p><p>Saving accepted bodies requires <code>--save-sample</code>.</p></section>
    <section class="install" aria-labelledby="install-title"><p class="eyebrow">RUN IT LOCALLY</p><h2 id="install-title">Start a bounded receiver</h2><p>Clone the <a href="https://github.com/B-Divyesh/sf-log-drain-contract-check">public source repository on GitHub</a>, then run the receiver:</p><pre tabindex="0"><code>git clone https://github.com/B-Divyesh/sf-log-drain-contract-check.git
cd sf-log-drain-contract-check
cargo run -- listen --duration 600 --port 8787</code></pre><p>Point your temporary HTTP drain to <code>http://127.0.0.1:8787/</code>.</p><p>Use <code>--ignore-field '$.request_id'</code> to suppress a reviewed false positive.</p></section>
  </main>`)}function S(){const r=new Map;for(const e of s.findings){const n=r.get(e.path)??[];n.push(e),r.set(e.path,n)}return[...r.entries()].map(([e,n])=>`<article><h3><code>${e}</code></h3><ul>${n.map(a=>`<li><p><span class="badge">${a.confidence.toUpperCase()}</span> ${a.detector}</p><p>${a.action}</p></li>`).join("")}</ul></article>`).join("")}function u(r="/demo"){p("Demo — Drain Check","Review the bundled Drain Check sample report without saving browser data.",r);const e=s.retention.find(t=>t.days===7),n=s.retention.find(t=>t.days===30),a=new Set(s.findings.map(t=>t.path)).size;return d(`<div class="demo-banner" role="status"><span>Demo — sample data, nothing is saved</span><button id="reset-demo" type="button">Reset demo</button><a href="/" data-route>View local setup</a></div>
    <main id="main" tabindex="-1" class="demo"><p class="eyebrow">SAMPLE REPORT / 10-MINUTE WINDOW</p><h1 tabindex="-1">Review this drain sample</h1><p class="lede">This report uses bundled checkout logs. It is separate from any real run.</p>
      <section class="metrics" aria-label="Sample summary"><div><strong>${s.events}</strong><span>events</span></div><div><strong>${s.events_per_second} / sec</strong><span>event rate</span></div><div><strong>${s.fields.length}</strong><span>field paths</span></div><div><strong>${s.findings.length}</strong><span>findings across ${a} fields</span></div></section>
      <section class="report" aria-labelledby="risk-title"><div><h2 id="risk-title">Review possible sensitive fields</h2><p>Detectors are conservative. A match needs a human decision.</p>${S()}</div><div><h2>Retention estimate</h2><p>At this sample rate and average event size:</p><dl><dt>7 days</dt><dd>about ${e.display}</dd><dt>30 days</dt><dd>about ${n.display}</dd></dl><h2>Generate a forwarding configuration</h2><p>Run this separate command after reviewing the report:</p><pre tabindex="0"><code>$ drain-check forwarding --url https://receiver.example/logs
# generic-http
# Send POST requests to this endpoint after report review
url = "https://receiver.example/logs"
method = "POST"
content_type = "application/json"</code></pre></div></section><p><a class="button" href="/" data-route>Read local setup</a></p>
    </main>`)}function h(r){const e=r==="privacy";return p(`${e?"Privacy":"Terms"} — Drain Check`,e?"How Drain Check handles drain samples and website data.":"Terms for using Drain Check.",`/${r}`),d(`<main id="main" tabindex="-1" class="prose"><p class="eyebrow">${e?"PRIVACY":"TERMS OF USE"}</p><h1 tabindex="-1">${e?"Privacy for local drain samples":"Terms for using Drain Check"}</h1>${e?"<p>The receiver binds to <code>127.0.0.1</code>.</p><p>It aggregates field names, types, counts, and detector results. It discards each body unless you pass <code>--save-sample</code>.</p><p>The website requests only files from this site. It writes no browser storage.</p>":"<p>Drain Check is free software under the MIT License. You decide where to point your drain and which data to save.</p><p>Secret detectors are warnings, not a guarantee. Review every match before forwarding production logs.</p>"}</main>`)}function k(){return p("Not found — Drain Check","Return to the Drain Check local receiver guide.",location.pathname),d('<main id="main" tabindex="-1" class="prose"><p class="eyebrow">404</p><h1 tabindex="-1">Page not found</h1><p>This address does not match a Drain Check page.</p><p><a class="button" href="/" data-route>Return home</a></p></main>')}function q(){const r=document.querySelector("#terminal-output");if(!r)return;const e=r.textContent??"";if(matchMedia("(prefers-reduced-motion: reduce)").matches){r.textContent=e;return}r.textContent="";let n=0;const a=window.setInterval(()=>{r.textContent=e.slice(0,n+=4),n>=e.length&&window.clearInterval(a)},16)}function c(r=!0){const e=location.pathname.replace(/\/$/,"")||"/",a=e==="/"&&new URLSearchParams(location.search).get("demo")==="1"?()=>u("/?demo=1"):e==="/"?$:e==="/demo"?u:e==="/privacy"?()=>h("privacy"):e==="/terms"?()=>h("terms"):k;o.innerHTML=a(),o.querySelectorAll("[data-route]").forEach(t=>t.addEventListener("click",i=>{i.preventDefault(),history.pushState({},"",t.href),c()})),o.querySelector("#reset-demo")?.addEventListener("click",()=>{localStorage.removeItem("demo:drain-check"),c()}),o.querySelector("#replay-demo")?.addEventListener("click",q),r&&o.querySelector("h1")?.focus(),v().textContent=document.title,scrollTo({top:0,behavior:"instant"})}addEventListener("popstate",()=>c());c(!1);
