(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const a of document.querySelectorAll('link[rel="modulepreload"]'))r(a);new MutationObserver(a=>{for(const i of a)if(i.type==="childList")for(const p of i.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&r(p)}).observe(document,{childList:!0,subtree:!0});function n(a){const i={};return a.integrity&&(i.integrity=a.integrity),a.referrerPolicy&&(i.referrerPolicy=a.referrerPolicy),a.crossOrigin==="use-credentials"?i.credentials="include":a.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function r(a){if(a.ep)return;a.ep=!0;const i=n(a);fetch(a.href,i)}})();const h=3,m=.005,y=[{path:"$",types:["object"],present_in:3},{path:"$.error",types:["string"],present_in:1},{path:"$.job",types:["object"],present_in:1},{path:"$.job.attempt",types:["integer"],present_in:1},{path:"$.job.name",types:["string"],present_in:1},{path:"$.job.ok",types:["boolean"],present_in:1},{path:"$.level",types:["string"],present_in:3},{path:"$.region",types:["string"],present_in:1},{path:"$.request",types:["object"],present_in:2},{path:"$.request.authorization",types:["string"],present_in:1},{path:"$.request.latency_ms",types:["integer"],present_in:2},{path:"$.request.method",types:["string"],present_in:2},{path:"$.request.path",types:["string"],present_in:2},{path:"$.request.user_email",types:["string"],present_in:1},{path:"$.service",types:["string"],present_in:3},{path:"$.timestamp",types:["string"],present_in:3},{path:"$.trace_id",types:["string"],present_in:1}],f=[{path:"$.request.authorization",detector:"secret-shaped value",confidence:"high",action:"Mask this value or exclude the field."},{path:"$.request.authorization",detector:"sensitive field name",confidence:"high",action:"Review this field before forwarding."},{path:"$.request.user_email",detector:"email-shaped value",confidence:"medium",action:"Confirm that this identifier belongs in the drain."}],g=[{days:7,estimated_bytes:571536,display:"558.1 KiB"},{days:30,estimated_bytes:2449440,display:"2.3 MiB"}],s={events:h,events_per_second:m,fields:y,findings:f,retention:g},o=document.querySelector("#app"),b=()=>document.querySelector("#route-status"),v="e6fac708cdc5",d=t=>`<a class="skip" href="#main">Skip to content</a>
  <header>
    <a class="wordmark" href="/" data-route aria-label="Drain Check home">DRΛIN<br>CHECK</a>
    <nav aria-label="Main navigation">
      <a href="/demo" data-route>Demo</a><a href="/#how">How it works</a><a href="/privacy" data-route>Privacy</a>
    </nav>
  </header>
  ${t}
  <footer>
    <p>Drain Check samples a log drain before you forward it.</p>
    <p><a href="/privacy" data-route>Privacy</a><span aria-hidden="true"> · </span><a href="/terms" data-route>Terms</a><span aria-hidden="true"> · </span>Built by Param Factory<span aria-hidden="true"> · </span>v0.1.0+${v}</p>
  </footer>
  <div id="route-status" class="sr-only" aria-live="polite"></div>`;function l(t,e,n){document.title=t,document.querySelector('meta[name="description"]').content=e,document.querySelector('link[rel="canonical"]').href=`https://log-drain-contract-check.sociobot.in${n}`,document.querySelector('meta[property="og:title"]').content=t,document.querySelector('meta[property="og:description"]').content=e,document.querySelector('meta[name="twitter:title"]').content=t,document.querySelector('meta[name="twitter:description"]').content=e}function w(){return l("Drain Check — inspect a log drain sample","Inspect a bounded local log drain sample before forwarding it.","/"),d(`<main id="main" tabindex="-1">
    <section class="hero">
      <div class="hero-copy">
        <p class="eyebrow">LOCAL PRE-FLIGHT / 10-MINUTE WINDOW</p>
        <h1 tabindex="-1">Inspect a log drain before forwarding</h1>
        <p class="lede">For platform teams who need volume, fields, and privacy risks before a drain stays on.</p>
        <p class="hero-action"><a class="button primary" href="/demo" data-route>Try it with sample data</a><span class="button-note">Opens a sample report. Nothing is saved.</span></p>
        <ul class="facts"><li>Listens only on your machine.</li><li>Discards bodies after aggregation.</li><li>Free under the MIT License.</li></ul>
      </div>
      <figure class="hero-art"><img src="/drain-console.webp" width="1024" height="1024" fetchpriority="high" alt="A pixel-art local receiver sorts log packets into review lanes."><figcaption>THE RECEIVER STAYS LOCAL</figcaption></figure>
    </section>
    <section class="terminal" tabindex="0" aria-labelledby="run-title" aria-describedby="run-help">
      <div class="terminal-bar"><span aria-hidden="true">●</span><span id="run-title">bundled sample / recorded run</span><button id="replay-demo" type="button">Replay recording</button></div>
      <p id="run-help" class="sr-only">A text recording of the bundled CLI demo. Use the replay button to play it again.</p>
      <pre tabindex="0"><code id="terminal-output">$ drain-check demo
Reviewed 3 events in 600s. 17 fields. 3 possible risks.
Report: /tmp/drain-check-demo-[unique]/report.json

$ drain-check forwarding --url https://receiver.example/logs
# generic-http
url = "https://receiver.example/logs"
method = "POST"</code></pre>
    </section>
    <section id="how" class="steps" aria-labelledby="how-title">
      <p class="eyebrow">THE SHORT PATH</p><h2 id="how-title">Review a drain in three steps</h2>
      <ol><li><strong>Listen locally.</strong><br>Run one bounded window.</li><li><strong>Read the contract.</strong><br>Check fields and likely secrets.</li><li><strong>Forward with intent.</strong><br>Use the generated template.</li></ol>
    </section>
    <section class="limits" aria-labelledby="limits-title"><h2 id="limits-title">What Drain Check does not do</h2><p>It does not store logs, search logs, or send them to a vendor.</p><p>Use <code>--save-sample</code> only when you choose to retain accepted bodies.</p></section>
    <section class="install" aria-labelledby="install-title"><p class="eyebrow">RUN IT LOCALLY</p><h2 id="install-title">Start a bounded receiver</h2><pre tabindex="0"><code>cargo install drain-check
# or clone this repository
cargo run -- listen --duration 600 --port 8787</code></pre><p>Then point your temporary HTTP drain to <code>http://127.0.0.1:8787/</code>.</p><p>Use <code>--ignore-field '$.request_id'</code> to suppress a reviewed false positive.</p></section>
  </main>`)}function $(){const t=new Map;for(const e of s.findings)t.set(e.path,e);return[...t.values()].map(e=>`<article><p><code>${e.path}</code> <span class="badge">${e.confidence.toUpperCase()}</span></p><p>${e.detector}</p><p>${e.action}</p></article>`).join("")}function k(){l("Demo — Drain Check","Review the bundled Drain Check sample report without saving data.","/demo");const t=s.retention.find(r=>r.days===7),e=s.retention.find(r=>r.days===30),n=new Set(s.findings.map(r=>r.path)).size;return d(`<div class="demo-banner" role="status"><span>Demo — sample data, nothing is saved</span><button id="reset-demo" type="button">Reset demo</button><a href="/" data-route>Start for real</a></div>
    <main id="main" tabindex="-1" class="demo"><p class="eyebrow">SAMPLE REPORT / 10-MINUTE WINDOW</p><h1 tabindex="-1">Review this drain sample</h1><p class="lede">This report uses bundled checkout logs. It is separate from any real run.</p>
      <section class="metrics" aria-label="Sample summary"><div><strong>${s.events}</strong><span>events</span></div><div><strong>${s.events_per_second} / sec</strong><span>event rate</span></div><div><strong>${s.fields.length}</strong><span>field paths</span></div><div><strong>${n}</strong><span>review fields</span></div></section>
      <section class="report" aria-labelledby="risk-title"><div><h2 id="risk-title">Review possible sensitive fields</h2><p>Detectors are conservative. A match needs a human decision.</p>${$()}</div><div><h2>Retention estimate</h2><p>At this sample rate and average event size:</p><dl><dt>7 days</dt><dd>about ${t.display}</dd><dt>30 days</dt><dd>about ${e.display}</dd></dl><h2>Forwarding template</h2><pre tabindex="0"><code>url = "https://receiver.example/logs"
method = "POST"
content_type = "application/json"</code></pre></div></section><p><a class="button" href="/" data-route>Read local setup</a></p>
    </main>`)}function u(t){const e=t==="privacy";return l(`${e?"Privacy":"Terms"} — Drain Check`,e?"How Drain Check handles drain samples and website data.":"Terms for using Drain Check.",`/${t}`),d(`<main id="main" tabindex="-1" class="prose"><p class="eyebrow">${e?"LOCAL DATA POLICY":"TERMS OF USE"}</p><h1 tabindex="-1">${e?"Your drain stays on your machine":"Use Drain Check at your own boundary"}</h1>${e?"<p>Drain Check binds to 127.0.0.1. It sends no analytics or log bodies anywhere.</p><p>The receiver aggregates field names, types, counts, and detector results. It discards each body after aggregation unless you pass <code>--save-sample</code>.</p><p>The website has no accounts, cookies, or tracking.</p>":"<p>Drain Check is free software under the MIT License. You decide where to point your drain and which data to save.</p><p>Secret detectors are warnings, not a guarantee. Review every match before forwarding production logs.</p>"}</main>`)}function S(){return l("Not found — Drain Check","Return to the Drain Check local receiver guide.",location.pathname),d('<main id="main" tabindex="-1" class="prose"><p class="eyebrow">404 / SIGNAL LOST</p><h1 tabindex="-1">That screen is not in this receiver</h1><p>Return to the local pre-flight guide.</p><p><a class="button" href="/" data-route>Return home</a></p></main>')}function C(){const t=document.querySelector("#terminal-output");if(!t)return;const e=t.textContent??"";if(matchMedia("(prefers-reduced-motion: reduce)").matches){t.textContent=e;return}t.textContent="";let n=0;const r=window.setInterval(()=>{t.textContent=e.slice(0,n+=4),n>=e.length&&window.clearInterval(r)},16)}function c(t=!0){const e=location.pathname.replace(/\/$/,"")||"/",n=e==="/"?w:e==="/demo"?k:e==="/privacy"?()=>u("privacy"):e==="/terms"?()=>u("terms"):S;o.innerHTML=n(),o.querySelectorAll("[data-route]").forEach(r=>r.addEventListener("click",a=>{a.preventDefault(),history.pushState({},"",r.href),c()})),o.querySelector("#reset-demo")?.addEventListener("click",()=>{localStorage.removeItem("demo:drain-check"),c()}),o.querySelector("#replay-demo")?.addEventListener("click",C),t&&o.querySelector("h1")?.focus(),b().textContent=document.title,scrollTo({top:0,behavior:"instant"})}addEventListener("popstate",()=>c());c(!1);
